{
 "title": "New dashboard",
 "time": { "from": "2025-01-05T12:41:59.185Z", "to": "2025-01-05T12:42:22.542Z" },
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "device_id",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"iot_data\",\r\n  tag: \"device_id\"\r\n)\r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature Trends of All Devices",
   "type": "timeseries",
   "description": "Temperature Trends of All Devices in intervals of 30s",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"temperature\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Humidity Trends of All Devices",
   "type": "timeseries",
   "description": "Humidity Trends of All Devices in intervals of 30s",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"humidity\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature for Device ${device_id}",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"temperature\" and r.device_id == \"${device_id}\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Temperature Trends for Device ${device_id}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"temperature\" and r.device_id == \"${device_id}\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Highest Temperature for Device ${device_id}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"temperature\" and r.device_id == \"${device_id}\")\r\n  |> max()\r\n"
    }
   ]
  },
  {
   "title": "Lowest Temperature for Device ${device_id}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"temperature\" and r.device_id == \"${device_id}\")\r\n  |> min()\r\n"
    }
   ]
  },
  {
   "title": "Humidity for Device ${device_id}",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"humidity\" and r.device_id == \"${device_id}\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Humidity Trends for Device ${device_id}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"humidity\" and r.device_id == \"${device_id}\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Highest Humidity for Device ${device_id}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"humidity\" and r.device_id == \"${device_id}\")\r\n  |> max()\r\n"
    }
   ]
  },
  {
   "title": "Lowest Humidity for Device ${device_id}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_data\" and r._field == \"humidity\" and r.device_id == \"${device_id}\")\r\n  |> min()\r\n"
    }
   ]
  }
 ]
}